@baseUrl = http://localhost:3000/api/users

@validEmail =user4.test@example.com
@validPassword =pass1234

### 1 LOGIN — success
POST {{baseUrl}}/login
Content-Type: application/json

{
    "email": "{{validEmail}}",
    "password": "{{validPassword}}"
}

### 2 LOGIN — missing credentials (expect 400)
POST {{baseUrl}}/login
Content-Type: application/json

{
    "email": "{{validEmail}}"
}

### 3 LOGIN — wrong password (expect 400)
POST {{baseUrl}}/login
Content-Type: application/json

{
    "email": "{{validEmail}}",
    "password": "wrongpassword"
}


### 4 LOGIN — user not found (expect 400)
POST {{baseUrl}}/login
Content-Type: application/json

{
    "email": "doesnotexist@example.com",
    "password": "password123"
}

### 5 CHECK SESSION — success
GET {{baseUrl}}/auth/me

### 6 CHECK SESSION — no token (expect 401)
GET {{baseUrl}}/auth/me
Cookie: accessToken=

### 7 CHECK SESSION — expired/invalid token
GET {{baseUrl}}/auth/me
Cookie: accessToken=this.is.not.a.valid.jwt

### 8 LOGOUT — success
POST {{baseUrl}}/logout

### 9 CHECK SESSION after logout — expect 401
GET {{baseUrl}}/auth/me

### View current user's address
GET http://localhost:3000/api/users/me/addresses