@baseUrl = http://localhost:3000/api

# =========================================================================
# AUTHENTICATION
# =========================================================================

### Login to get token
POST {{baseUrl}}/users/login
Content-Type: application/json

{
    "email": "spolmag@gmail.com",
    "password": "pass1234"
}

### User log out -> clear token
POST {{baseUrl}}/users/logout
Content-Type: application/json

{
    "email": "user7.test@example.com",
    "password": "pass1234"
}

# =========================================================================
# CART API TESTS (Requires @authToken)
# =========================================================================

### 1. Get Current User's Cart
GET {{baseUrl}}/carts

### 2. Add an Item to Cart
POST {{baseUrl}}/carts
Content-Type: application/json

{
  "productId": "6a1914e63b9010b699421c84",
  "quantity": 2
}

### 3. Update Cart Item Quantity (Delta adjustments: use positive or negative values)
PATCH {{baseUrl}}/carts/quantity/6a1914e63b9010b699421c84
Content-Type: application/json

{
  "quantity": 3
}

### 4. Edit Cart Item Quantity (Direct Override / Set to 0 to delete item)
POST {{baseUrl}}/carts/edit
Content-Type: application/json

{
  "productId": "6a1914e63b9010b699421c84",
  "quantity": 0
}

### 5. Remove Single Item From Cart (Drop Completely)
POST {{baseUrl}}/carts/remove
Content-Type: application/json

{
  "productId": "6a1914e63b9010b699421c84"
}

### 6. Clear Entire Cart Array
POST {{baseUrl}}/carts/clear

# =========================================================================
# ORDER API TESTS (Requires @authToken)
# =========================================================================

### 7. Create New Order From Cart Details (Purges Cart and sets Order to Pending)
POST {{baseUrl}}/orders/checkout
Content-Type: application/json

{
  "paymentMethod": "Bank transfer"
}

### 10. Get All System Orders (Admin view - sorted newest first)
GET {{baseUrl}}/orders/all

### Update order detail & change order status to paid (update products stock)
PUT {{baseUrl}}/orders/6a24113a3475e908ecc5e09b
Content-Type: application/json

{
  "status": "Paid"
}

### 9. Admin changes status to On Delivery or Delivered (No stock actions taken)
PUT {{baseUrl}}/orders/65cd9876543210fedcba8765
Content-Type: application/json

{
  "status": "On delivery"
}

### 10. Admin cancels order (Restocks database inventory because status was Paid)
PUT {{baseUrl}}/orders/"65cd9876543210fedcba8765"
Content-Type: application/json

{
  "status": "Cancelled"
}

