
### Get all products
GET http://localhost:3000/api/products

### Get products: filter by name or part of name
GET http://localhost:3000/api/products?productname=chicken

### Get products: Combined filtering (Category + Query + Sort)
GET http://localhost:3000/api/products?categoryId=6a1858cee42d6e025143d78a&productname=oil&sort=price_asc

### Get products: filter by categoryId
GET http://localhost:3000/api/products?categoryId=6a1858bc63cbfad8097bf4ea


### Get products: Sort by price (asc: cheapest first, dsc: highest first)
GET http://localhost:3000/api/products?sort=price_asc

### Get product by id
GET http://localhost:3000/api/products/6a17f760a0b9d736a566ce58

### create new product
POST http://localhost:3000/api/products
Content-Type: application/json

{      
    "productname":"test",
    "price":380,
    "categoryId":"6a1858cee42d6e025143d78a",
    "quantity": 1,
    "kcal":10,
    "protein":"0g",
    "carbs":"30g",
    "fat":"8g",
    "tag":"",
    "desc":"Test",
    "imageUrl":"aaaa",
    "isActive":false
}

### update product
PUT http://localhost:3000/api/products/6a19117e3b9010b699421c82
Content-Type: application/json

 {"productname": "อกไก่ปั่น ข้าวกล้อง",
    "price": 199,
    "isActive":true
 }

### delete product
DELETE http://localhost:3000/api/products/6a1d2af89115c5dfade23466
